### ISSUE TITLE
Transparancy issues

### ISSUE THREAD

**Issue by kirvis250** [asis5528/Path_Generator#1]
As you wrote in fb
`GLES31.glClearColor(0, 0, 0, 1f);` needs to be replaced with `GLES31.glClearColor(0, 0, 0, 0f);
`
But also in OpenGLView you have to set few parameters before setting renderer. 

```
setEGLConfigChooser(8, 8, 8, 8, 16, 0);
getHolder().setFormat(PixelFormat.TRANSPARENT);
setZOrderOnTop(true);
```

soruce: https://stackoverflow.com/questions/2034822/android-opengl-es-transparent-background

**Comment by asis5528** [comment]
weird, it works fine just with GLES31.glClearColor(0, 0, 0, 0f); for transparancy.

**Comment by asis5528** [comment]
Looks like it only works GLES31.glClearColor(0, 0, 0, 0f); in desktopsfor transparancy.I will update that in OpengGLView.

**Comment by asis5528** [comment]
Fixed
