### ISSUE TITLE
Sharp corner glitch

### ISSUE THREAD

**Issue by kirvis250** [asis5528/Path_Generator#3]
With paths, that have sharp turns, there is a problem that corner is too sharp (sharp to infinity). 

![Screenshot_20191121-125050](https://user-images.githubusercontent.com/6008835/69331539-9e90c100-0c5d-11ea-971d-08f2ee100069.png)

Basically there are two cases of the same problem: 

1. Very sharp edge causes this nearly infinite continuation of line. 
2. If you go full 180 continuation is infinite and thus the segment isn't drawn. 

Experimental data set:

```java
 float[] updated_coordinates;
updated_coordinates = new float[]{ -1.0f, -1.0f, -1.0f, -1.0f, -0.5f, 0.5f, -0.9921875f, -0.9921875f, -0.47265625f, 0.47265625f, 0.0f, 0.0f, 0.0f, 1.0f, 0.5f, 0.0f, 0.0f, -1.0f, 0.0f, -0.5f, 0.5f, 0.5f,
0.78125f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f }
```

For subdivisions everything is 1.0f (on)

EXACT USED CODE: 

  ```java
float[] updated_coordinates;
float[] updated_subdivision;

List<Point> array = new ArrayList<Point>();
array.add(new Point(-256, -256));
array.add(new Point(-256, -256)); 
array.add(new Point(-128, 128)); // problematic area
array.add(new Point(-254, -254)); // problematic area
array.add(new Point(-121, 121)); // problematic area
array.add(new Point(0, 0));
array.add(new Point(0, 256));
array.add(new Point(128, 0));
array.add(new Point(0, -256));
array.add(new Point(0, -128));
array.add(new Point(128, 128));
array.add(new Point(200, 0));
array.add(new Point(256, 256));
array.add(new Point(256, 256));

updated_coordinates = new float[array.size() * 2 ];
updated_subdivision = new float[ (array.size()) * 16];

for (int i = 0 ; i < array.size(); i++) {
      updated_coordinates[i * 2] = array.get(i).x / 256.00f;
      updated_coordinates[i * 2 + 1] = array.get(i).y / 256.00f;
      updated_subdivision[i * 16] = 1f;

       for (int jg = 1; jg < 16; jg++) {
             updated_subdivision[i * 16 + jg] = 0f;
       }
}
```

**Comment by asis5528** [comment]
Corner actually breaks when two neighbor paths overlap each other coz pivot is in the middle of quads. One fix is by duplicating the points that are causing the paths to overlap. Like this:
 ```java
                                float[] updated_coordinates;
                                float[] updated_subdivision;

                                List<Point> array = new ArrayList<Point>();
                              
                                array.add(new Point(-256, -256));
                                array.add(new Point(-256, -256));
                                array.add(new Point(-128, 128));// problematic area
                                array.add(new Point(-128, 128));// problematic area
                                array.add(new Point(-254, -254));//problematic area
                                array.add(new Point(-254, -254));// problematic area
                                array.add(new Point(-121, 121)); 
                                array.add(new Point(0, 0));
                                array.add(new Point(0, 256));
                                array.add(new Point(128, 0));
                                array.add(new Point(0, -256));
                                array.add(new Point(0, -128));
                                array.add(new Point(128, 128));
                                array.add(new Point(200, 0));
                                array.add(new Point(256, 256));
                                array.add(new Point(256, 256));

                              

                                updated_coordinates = new float[array.size() * 2 ];
                                updated_subdivision = new float[ (array.size()) * 16];

                                for (int i = 0 ; i < array.size(); i++) {
                                    updated_coordinates[i * 2] = array.get(i).x / (256.00f);
                                    updated_coordinates[i * 2 + 1] = array.get(i).y / (256.00f);
                                    updated_subdivision[i * 16] = 1f;

                                    for (int jg = 1; jg < 16; jg++) {
                                        updated_subdivision[i * 16 + jg] = 0f;
                                    }
                                }
```

If it will be possible to fix it from a shader, I will try it.

**Comment by asis5528** [comment]
@kirvis250  check this 
asis5528/Path_Generator@672563a2333c010bd5b004af1453fdc0d536dd1a

**Comment by kirvis250** [comment]
It kind of works in most cases, But when i zoom out (have more data per tile) it somehow loses stability. 

![Screenshot_20191125-122918](https://user-images.githubusercontent.com/6008835/69532875-694ae280-0f7f-11ea-8124-49f1160be7f5.png)

**Comment by kirvis250** [comment]
Also (it probably should be separate issue but whatever) The path width should be always the same With this fix the problem is more noticeable than it was before. 

In perfect conditions this wouldn't be the problem since there is a quite big path points density. But if we optimize points amount by changes in bearing, then even slightest deviation would cause anomalies when instead of rectangle path we get Triangle or some weird trapezoid.

**Comment by asis5528** [comment]
@kirvis250 can u send me the path coordinates that occur this problem?

**Comment by kirvis250** [comment]
Okey Image as rendered looks like this:

![Screenshot_20191125-150428](https://user-images.githubusercontent.com/6008835/69543197-c2be0c00-0f95-11ea-9297-e0312a422fbb.png)

Dataset used: 
[bugDataFile.zip](https://github.com/asis5528/Path_Generator/files/3886725/bugDataFile.zip)

That's zipped one text file with vertices and subdivisions arrays (formatted as Java code)

**Comment by asis5528** [comment]
is subdivision count just one?

**Comment by kirvis250** [comment]
Yes. Array is for 16 subdivisions as written in documentation.

**Comment by asis5528** [comment]
![image](https://user-images.githubusercontent.com/19802044/69548912-615f6280-0fc0-11ea-9374-64913e91a332.png)
it looks fine for me ,may be u increased width too much?

**Comment by kirvis250** [comment]
0.04 line width is already causes the spike to show and if i set 0.05 spike gets even longer.

**Comment by asis5528** [comment]
so spikes is only the problem?

**Comment by kirvis250** [comment]
No.

Even before fix of sharp turns one issue was present. Path width should be consistent. I mean that one path segment essentially should be rectangle and only joints can be rounded.

![Screenshot_20191127-103750](https://user-images.githubusercontent.com/6008835/69707535-a1c6f980-1102-11ea-8f87-27d6a1523d2e.png)

**Comment by asis5528** [comment]
ye that should be equal....will fix that ,that's coz of angle

**Comment by asis5528** [comment]
check this asis5528/Path_Generator@b3b2c0be4cfbf5efe104049800f8588ef0677d1a

**Comment by kirvis250** [comment]
Width wise this looks correct

**Comment by asis5528** [comment]
and i can't find the issue with spikes ...pretty weird

**Comment by kirvis250** [comment]
Eliminating every all sequential points that are in same pixel didn't worked. 

Also there is another problem. At some points path cuts out. It is seen in screenshots.

**Comment by kirvis250** [comment]
```java
 updated_coordinates = new float[]{ -0.63914645f, 0.3668328f, -0.6440686f, 0.37344944f, -0.64887744f, 0.379914f, -0.65387523f, 0.38663185f, -0.6587596f, 0.39319777f, -0.66358745f, 0.3996877f, -0.6684153f, 0.40617764f, -0.6735453f, 0.41307282f, -0.6784675f, 0.41968954f, -0.68338966f, 0.4263062f, -0.68827415f};
```

line width = 0.35f

**Comment by kirvis250** [comment]
```java 

                        updated_coordinates = new float[]{ -0.63914645f, 0.3668328f, -0.63914645f, 0.3668328f, -0.6440686f, 0.37344944f,
                                -0.64887744f, 0.379914f, -0.65387523f, 0.38663185f, -0.6587596f, 0.39319777f, -0.66358745f, 0.3996877f, -0.6684153f
                                , 0.40617764f, -0.6735453f, 0.41307282f, -0.6784675f, 0.41968954f, -0.68338966f, 0.4263062f, -0.68338966f, 0.4263062f};

```

**Comment by kirvis250** [comment]
https://github.com/kirvis250/Path_Generator/tree/some_changes

**Comment by asis5528** [comment]
so having high number of coordinates in small distance shape is creating jittering issue  or unstable shape ....... so, removing some coordinates between less distance path will solve that unstable problem ..... when paths are zoomed in , the coordinates are not that dense so the unstable path isn't appeared ..but when paths are zoomed out , there are lots of dense coordinates within small shape ...so removing coordinates or increasing distance between coordinates while zoomed out will solve the issue

**Comment by asis5528** [comment]
Here you can see the distance between these three coordinates are way smaller so it's causing unstable or jittering issue.
![image](https://user-images.githubusercontent.com/19802044/71010783-6bced100-2114-11ea-8d86-2471d6e8b78f.png)

here I added increased the distance between coordinates and no issue has appeared.
![image](https://user-images.githubusercontent.com/19802044/71010893-9de03300-2114-11ea-8f78-2ebc766f01f4.png)

**Comment by kirvis250** [comment]
So basically checking if two coordinates are in same pixel is meaningless and should be replaced with exact min distance?

I will do that today

**Comment by kirvis250** [comment]
Didn't worked out.  reproduced with quite higher distance between coordinates. 

maybe some operation with coordinates returns bad value or something. When i attempt to do rounding on coordinates it begins to display things correctly. 

``` java
                        updated_coordinates = new float[]{
                                0.29155f, -0.6961f,
                                0.29155f, -0.6961f,
                                0.20237267f, -0.5279025f,
                                0.17981756f, -0.4853418f,
                                0.15687752f, -0.44205475f,
                                0.00112f, -0.1481f,
                                0.00112f, -0.1481f
                        };
```

I will Try one another thing in two hours. (Rounding of coordinates).

**Comment by asis5528** [comment]
hmm ....i think it needs more distance....but i will think if i can do anything from gpu ..

**Comment by kirvis250** [comment]
Okey I produced quite decent bug reproduction data:

``` java

updated_coordinates = new float[]{

                // start point
                0.57f, -1.16f,
                0.57f, -1.16f,

                // first Hole
                0.41f, -0.91f,
                0.38f, -0.86f,
                0.35f, -0.81f,

                // second Hole
                -0.14f, 0.11f,
                -0.17f, 0.17f,
                -0.2f, 0.23f,

                // third Hole
                -0.31f, 0.44f,
                -0.34f, 0.5f,
                -0.37f, 0.56f,

                // end point
                -0.4f, 0.61f,
                -0.4f, 0.61f
        };
```
On phone it looks like this:
![Screenshot_20191218-152028](https://user-images.githubusercontent.com/6008835/71089786-3c6aa380-21aa-11ea-8f39-da3c907cf98c.png)


I used Line width on my app for reproduction:  0.111  (original : 0.11395125). In any case width doesn't have any affect on problem. 

For ensuring that two points will not be too close each other i used Pythagorean theorem to determine distance between last added point and current (iterating through all the points)  and added point only if distance is greater than 0.05 (measures for final data that will be given to shader).

**Comment by asis5528** [comment]
I see, on pc this coords works fine ....but in android, it has that bug .....but if the distance is greater or equal to 0.05 , it works fine .... as given above bug data ,distance between( -0.17f, 0.17f) and (-0.2f, 0.23f) is 0.4011

**Comment by kirvis250** [comment]
I only wrote what rules i applied to get such data. And i set that mind distance of 0.05 basically randomly. It probably should be something like 0.02 or 0.03.

And for the record distance between ` (-0.17f, 0.17f)` and  `(-0.2f, 0.23f)` is `0.067082039` and not 
`0.4011` or `0.04011`. 

I used this formula: [link to pdf](https://orion.math.iastate.edu/dept/links/formulas/form2.pdf)

`
sqrt((-0.17 -  -0.2f)^2 + (0.17 - 0.23)^2) = 
sqrt((0,03)^2 + (−0,06)^2) = 
sqrt(0,0009 + 0,0036) = 
sqrt(0,0045) =  0,067082039
`

Sqrt - Square root
^2 - power by two

**Comment by asis5528** [comment]
Oh ye, I just checked it, my bad ..... I think, I didn't put correct values ..... yesterday I invested in a new method for creating polylines, I will update the code when it's done ....

i actually did between (-0.17,-0.17) and (-0.2,0.23) ......i should have been more careful

**Comment by kirvis250** [comment]
I just fully reproduced the bug.

All theses holes has one thing in common - Three coordinates that are on the same straight line. 

Checked by calculating area of triangle.

Validated with Few data sets:

``` java

                        updated_coordinates = new float[]{

                                // meaningless start point
                                0.9f, -0.8f,
                                0.9f, -0.8f,

                                // Collinear coordinates
                                0.55f, -0.55f,
                                0.45f, -0.45f,
                                0.20f, -0.20f,

                                // meaningless end point
                                -0.9f, 0.8f,
                                -0.9f, 0.8f
                        };
```


``` java 
                  updated_coordinates = new float[]{

                       // meaningless start point
                                0.9f, -0.8f,
                                0.9f, -0.8f,

                        // Collinear coordinates
                                0.60f, -0.30f,
                                0.50f, -0.25f,
                                0.20f, -0.10f,

                             // meaningless end point
                                -0.9f, 0.8f,
                                -0.9f, 0.8f
                        };

```

**Comment by asis5528** [comment]
Made new method to rendering paths..changes in path.glsl 

asis5528/Path_Generator@91b513d753659c1a242c0953fe288dbd8b3722a1

**Comment by asis5528** [comment]
This is for testing ,if bugs doesn't appear i will write code properly and add the  feature for subdivision later.....For this you will have to follow new rule ..

first index value always should be equal to second index value+episilon value i.e 0.0001
and same for last and second last index ...



so ,previously coordinates were like :
```
 updated_coordinates = new float[]{

                       // meaningless start point
                                0.9f, -0.8f,
                                0.9f, -0.8f,

                        // Collinear coordinates
                                0.60f, -0.30f,
                                0.50f, -0.25f,
                                0.20f, -0.10f,

                             // meaningless end point
                                -0.9f, 0.8f,
                                -0.9f, 0.8f
                        };
```

for new method , coordinates should be written as:
```
 updated_coordinates = new float[]{

                       // meaningless start point
                                0.9f+0.0001, -0.8f+0.0001,
                                0.9f, -0.8f,

                        // Collinear coordinates
                                0.60f, -0.30f,
                                0.50f, -0.25f,
                                0.20f, -0.10f,

                             // meaningless end point
                                -0.9f, 0.8f,
                                -0.9f+0.0001, 0.8+0.0001f
                        };
```

**Comment by kirvis250** [comment]
It looks like it worked. But that Previous issue of sharp to infinity corner came back.

**Comment by asis5528** [comment]
ah that one .... I'm working in miterlimit ,i will update when it will work

**Comment by asis5528** [comment]
check this out:
asis5528/Path_Generator@7c5e519df798adcd4c67fc14aec3d9bf6475b503

**Comment by asis5528** [comment]
All intersection between segment will be seen with this method

**Comment by kirvis250** [comment]
Setting MitterLimit to -1.0 works for these infinite corners. 

 Is it possible to some how make it work so those intersections wouldn't be visible?

**Comment by asis5528** [comment]
Actually, i was working on that but couldn't make it ...But I have couples of idea in mind,i will test that later ..also i have to think that this code works properly for subdivision path too later...

**Comment by asis5528** [comment]
check this out:
asis5528/Path_Generator@fc79cd8e582c9f54fbecc6c4837a5cd0ea33bea8

Rules for coordinates are the same with the first rule we had..
first index = second index
last index = second last index

**Comment by asis5528** [comment]
Check this:
asis5528/Path_Generator@51aacb038dcdbdfc4f9190d11fcba73fd6f9f840

**Comment by asis5528** [comment]
Now almost all are in the final stage .....
Things to note:
1) Subdivision max limit is 64.
2) Some devices don't support more than 16 attributes data  so we have to send only 48  subdivision

We can check the max attribute count of the device from Bitam.max_att; 

![image](https://user-images.githubusercontent.com/19802044/71312094-537def80-244f-11ea-9d71-2e0e25c7e991.png)
We can check the attribute count of devices from here...

![image](https://user-images.githubusercontent.com/19802044/71312129-8fb15000-244f-11ea-8af8-6697bd1bc475.png)
Actually attribute count of devices is done from Opengl Renderer..........
